# Generated by Django 3.2.24 on 2024-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalreport',
            fields=[
                ('hospital_report_id', models.AutoField(db_column='hospital report_id', primary_key=True, serialize=False)),
                ('report', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'hospitalreport',
                'managed': False,
            },
        ),
    ]
