# Generated by Django 3.2.24 on 2024-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencynumber',
            fields=[
                ('emergency_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_no', models.IntegerField()),
            ],
            options={
                'db_table': 'emergencynumber',
                'managed': False,
            },
        ),
    ]
